### ISSUE TITLE
Nextgen launcher

### ISSUE THREAD

**Issue by keeganwitt** [groovy/groovy-native-launcher#1]
I'd like to simplify the launcher and make it more flexible.  In particular, I don't like the coupling of the program arguments with the executables, as these can vary from Groovy version to Groovy version.  Originally, I was thinking of replacing these native binaries with Launch4J, but that wouldn't take advantage of all the GROOVY_HOME, JAVA_HOME, etc work that is already present in the Groovy batch files.  Now I'm thinking a wrapper exe that's just a passthrough to the batch file might be a better solution.

**Comment by keeganwitt** [comment]
I haven't decided yet if the permanent home will be in this repo or in [groovy-windows-installer](https://github.com/groovy/groovy-windows-installer), but I'm testing out a replacement [here](https://github.com/keeganwitt/groovy-binaries).

**Comment by akaranta** [comment]
The coupling of the executable with the program argument definitions is a compromise. The benefit gained is that the launcher is able to pass the rest of the parameters to the jvm, thus enabling the invoker to pass both groovy and jvm parameters in whatever order.

The parameter descriptions are fairly easy to modify (add/remove), but it does require a recompilation.

The original intent was to have just a single executable file. If this is given up, it would be quite easy to modify the launcher so that the parameter descriptions (for the parameters passed to groovy, not to jvm) would be loaded from a configuration file (colocated with the executable). If this is chosen as the way to go by whomever nowadays maintains the windows installer (which I would guess is the main usage for the native launcher), I can help with this.

**Comment by keeganwitt** [comment]
I understand it's a trade-off.  I wasn't trying to imply existing binaries were a bad solution, just that I wasn't sure the advantages were worth the added complexity.  That's part of why I was hesitant to replace the original repo -- it kinda has a larger scope than my proposed solution.   What makes you prefer the existing solution?  More flexibility for JVM args?
Oh, and do you know how the existing binaries should be built?  There's a Makefile, but it appears to be a placeholder.

I'm the maintainer of the Windows installer, and yea, I think it's pretty much the only use-case for binaries at this point.  That being the case, do you feel there's any advantage to the existing binaries vs Launch4J?

**Comment by akaranta** [comment]
Passing jvm arguments as they are (not having to prefix them with -J or such) is IMO nice. The native launcher also looks for jvm to use from PATH and windows registry (if JAVA_HOME is not set).
Also both 32 and 64 bit binaries can be built (to utilize 32 and 64 bit jvms respectively). Launch4J does not need this as (if I understood correctly) launcher a new Java process to run the program. The Groovy native launcher otoh is a java.exe clone in that it loads the virtual machine in the same process and runs the program there. Slightly faster and more memory efficient, but hardly an issue these days.

Yes, I do know how the binaries are built. I am the original author of the C-code. The build was written by Russel Winder. I recall that we documented it, but either it has gotten lost along the way or then we didn't. 
The build uses scons (http://scons.org/). As a compiler (on windows) one can either use gcc (installing mingw+msys (http://www.mingw.org/wiki/msys)) or ms visual c++ compiler (installing visual studio for c++ development). Scons will detect which one is installed (one can force usage of one or the other with a commandline param. I do not right now remember what it was, but "scons help" will tell). So, just running "scons" in the sources root directory (where the Sconstruct - script is located) will run the build. There are also some tests that can be run with "scons test".
The native launcher also compiles on os-x, linux and solaris (to binaries of the corresponding platforms, i.e. there's no cross compilation support for e.g. producing windows binaries on linux).

If windows is the only target platform, then launch4j might be a very good alternative - less code to maintain is always better. I have no experience in configuring launch4j to create an executable (seems to be quite a few options there) so I have no idea how much trouble that is. But it's a one shot - once done, I think you can just keep using the same binary (or easily rebuild it).
Although the native launcher code base is pretty stable (no known issues) and producing the binaries is pretty fast and simple once you have the correct toolchain installed. But there is the drag of having to update the parameter definitions in groovy.c whenever the parameters groovy accepts are changed.

I don't presently have the necessary toolchain on the computer(s) I have at hand, but installing them should not take too long. If you decide to go with Launch4j that's ok, then I won't bother doing anything about this repo. Your project (the windows installer), your call. :)

**Comment by keeganwitt** [comment]
Do you know why the resource files reference afxres.h instead of windows.h?

**Comment by akaranta** [comment]
IIRC it was either generated by visual studio or taken from some example. As it worked I paid it no further thought. I think Windows.h will itself include afxres.h so using that should work also.
The main thing the resource files were used for was to get groovy icon to the executable.

**Comment by keeganwitt** [comment]
I'm gonna go ahead and close this issue, per our discussion, if I replace this, I'll do so within the context of the Windows installer project.
